config/routes.rb
Rails.application.routes.draw do
  resources :highlights
  resources :scripts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/highlight.rb
class Highlight < ApplicationRecord
  belongs_to :script
end

app/models/script.rb
class Script < ApplicationRecord
  has_many :highlights
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  before_action :set_highlight, only: [:show, :edit, :update, :destroy]

  # GET /highlights
  # GET /highlights.json
  def index
    @highlights = Highlight.all
  end

  # GET /highlights/1
  # GET /highlights/1.json
  def show
  end

  # GET /highlights/new
  def new
    @highlight = Highlight.new
  end

  # GET /highlights/1/edit
  def edit
  end

  # POST /highlights
  # POST /highlights.json
  def create
    @highlight = Highlight.new(highlight_params)
    @script = Script.find(@highlight.script_id)

    respond_to do |format|
      if @highlight.save
        format.html { redirect_to @highlight, notice: 'Highlight was successfully created.' }
        format.json { render :show, status: :created, location: @highlight }
      else
        format.html { render :new }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highlights/1
  # PATCH/PUT /highlights/1.json
  def update
    respond_to do |format|
      if @highlight.update(highlight_params)
        format.html { redirect_to @highlight, notice: 'Highlight was successfully updated.' }
        format.json { render :show, status: :ok, location: @highlight }
      else
        format.html { render :edit }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highlights/1
  # DELETE /highlights/1.json
  def destroy
    @highlight.destroy
    respond_to do |format|
      format.html { redirect_to highlights_url, notice: 'Highlight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highlight
      @highlight = Highlight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highlight_params
      params.require(:highlight).permit(:text, :color_code, :comment, :script_id)
    end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy]

  # GET /scripts
  # GET /scripts.json
  def index
    @scripts = Script.all
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
  end

  # GET /scripts/new
  def new
    @script = Script.new
  end

  # GET /scripts/1/edit
  def edit
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(script_params)

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render :show, status: :created, location: @script }
      else
        format.html { render :new }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1
  # PATCH/PUT /scripts/1.json
  def update
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to @script, notice: 'Script was successfully updated.' }
        format.json { render :show, status: :ok, location: @script }
      else
        format.html { render :edit }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script.destroy
    respond_to do |format|
      format.html { redirect_to scripts_url, notice: 'Script was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_script
      @script = Script.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def script_params
      params.require(:script).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/highlights/_form.html.erb
<%= form_for(highlight) do |f| %>
  <% if highlight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(highlight.errors.count, "error") %> prohibited this highlight from being saved:</h2>

      <ul>
      <% highlight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p class='highlight'>Highlight</p>
  <div class='popup'>
    <div class='fields'>
      <%= f.text_field :text %>
      <%= f.text_field :color_code%>
      <%= f.text_field :comment%>
    </div>
    <div class='fields'>
      <%= f.text_field :script_id, placeholder: "#{@script.id}" %>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/highlights/edit.html.erb
<h1>Editing Highlight</h1>

<%= render 'form', highlight: @highlight %>

<%= link_to 'Show', @highlight %> |
<%= link_to 'Back', highlights_path %>

app/views/highlights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Highlights</h1>

<table>
  <thead>
    <tr>
      <th>Item title</th>
      <th>Item color</th>
      <th>Item comment</th>
    </tr>
  </thead>

  <tbody>
    <% @highlights.each do |highlight| %>
      <tr>
        <td><%=highlight.text%></td>
        <td><%=highlight.color_code%></td>
        <td><%=highlight.comment%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Highlight', new_highlight_path %>

app/views/highlights/new.html.erb
<h1>New Highlight</h1>

<%= render 'form', highlight: @highlight %>

<%= link_to 'Back', highlights_path %>

app/views/highlights/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_highlight_path(@highlight) %> |
<%= link_to 'Back', highlights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scriptmanager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header></header>
    <%= yield %>
    <footer></footer>
  </body>
</html>

app/views/scripts/_form.html.erb
<%= form_for(script) do |f| %>
  <% if script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
      <% script.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class=fields>
    Title: <%= f.text_field :title %>
    Content: <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scripts/edit.html.erb
<h1>Editing Script</h1>

<%= render 'form', script: @script %>

<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %>

app/views/scripts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Scripts</h1>

    <% @scripts.each do |script| %>
      <h2><%= script.title %><h2>
      <p><%= script.content %></p>
      <%= link_to 'Show', script %>
      <%= link_to 'Edit', edit_script_path(script) %>
      <%= link_to 'Destroy', script, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

app/views/scripts/new.html.erb
<h1>New Script</h1>

<%= render 'form', script: @script %>

<%= link_to 'Back', scripts_path %>

app/views/scripts/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @script.title %><h2>
<p><%= @script.content %></p>

<%= link_to 'Edit', edit_script_path(@script) %> |
<%= link_to 'Back', scripts_path %>

<%= render 'highlights/form', highlight: @script.highlights.build %>